openapi: 3.0.1
info:
  title: Book Shop
  description: CRUD API.
  version: 1.0.0
servers:
  - url: /v2
paths:
  /book:
    get:
      summary: Get Books
      operationId: getBooks
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDto'
    post:
      summary: Add a Book
      operationId: addBook
      requestBody:
        description: Book to be added in shop
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookDto'
        required: true
      responses:
        200:
          description: Book Added
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: book
  /users:
    get:
      summary: Get Users
      operationId: getUsers
      responses:
        200:
          description: Successfully operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'

    post:
      summary: Add User
      operationId: addUser
      requestBody:
        description: User to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
        required: true
      responses:
        200:
          description: User Added
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/UserDto'
components:
  schemas:
    BookDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: Oathbringer
        author:
          type: string
          example: Brandon Sanderson

    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        address:
          type: string
          example: Random Address